services:

  waf:
    image: owasp/modsecurity-crs:nginx
    container_name: waf
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/waf.conf
    networks:
      - app
    depends_on:
      - sqli-vuln
      - xss-vuln

  sqli-vuln:
    build: ./sqli-vuln
    expose:
      - "5000"
    networks:
      - app

  xss-vuln:
    build: ./xss-vuln
    expose:
      - "5000"
    networks:
      - app

networks:
  app:
